# Generated by Django 4.0.6 on 2022-07-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=250)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('book_pages', models.IntegerField(blank=True, null=True)),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('retal_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('retal_peroid', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('rented', 'rented'), ('sold', 'sold')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
