# Generated by Django 4.0.6 on 2022-07-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
